export const pageTitles = {
  "/": "Home",
  "/dashboard": "Dashboard",
  "/budget-plans": "Budget Plans",
  "/events": "Events",
  "/expenses": "Expenses",
  "/incomes": "Incomes",
  "/transfers": "Transfers",
  "/goals": "Goals",
  "/recommendations": "Recommendations",
  "/settings": "Settings",
  "/settings/auto-plan-rules": "Auto Plan Rules",
  "/report": "Monthly Report",
  "/profile": "Profile",
};
